// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pmService.Models;

#nullable disable

namespace PmServiceNetCode.Migrations
{
    [DbContext(typeof(MaznetModel))]
    [Migration("20260926040146_AddEndpointPermissions")]
    partial class AddEndpointPermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PmServiceNetCode.Models.Endpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Endpoints");
                });

            modelBuilder.Entity("PmServiceNetCode.Models.EndpointPermission", b =>
                {
                    b.Property<int>("EndpointId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("EndpointId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("EndpointPermissions");
                });

            modelBuilder.Entity("PmServiceNetCode.Models.Form", b =>
                {
                    b.Property<int>("IdForm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Form");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdForm"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Onvan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdForm");

                    b.ToTable("Tbl_Forms", (string)null);
                });

            modelBuilder.Entity("PmServiceNetCode.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("PmServiceNetCode.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PmServiceNetCode.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("PmServiceNetCode.Models.TblFarayand", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Grouh")
                        .HasColumnType("int");

                    b.Property<string>("NameSabtKonande")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Onvan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TarikhSabt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Tbl_Farayand");
                });

            modelBuilder.Entity("PmServiceNetCode.Models.User", b =>
                {
                    b.Property<int>("Code_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code_User"));

                    b.Property<int?>("AccessLevel")
                        .HasColumnType("int");

                    b.Property<int?>("Flag_N")
                        .HasColumnType("int");

                    b.Property<string>("Name_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("code_Role")
                        .HasColumnType("int");

                    b.Property<int?>("code_bakhsh")
                        .HasColumnType("int");

                    b.Property<int?>("code_omor")
                        .HasColumnType("int");

                    b.Property<int?>("no_karbar")
                        .HasColumnType("int");

                    b.HasKey("Code_User");

                    b.ToTable("tbl_User");
                });

            modelBuilder.Entity("PmServiceNetCode.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("pmService.Models.Tbl_Derakht_Tajhizat", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<int?>("Bazdid")
                        .HasColumnType("int");

                    b.Property<int?>("Code_No_DerakhtTajhizat")
                        .HasColumnType("int");

                    b.Property<string>("Code_Pm")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Field_Rabet")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("Goroh_Tajhiz")
                        .HasColumnType("int");

                    b.Property<string>("Name_Jadval_Pm")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name_Layeh_Gis")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name_Pm")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("Parent_tajhiz")
                        .HasColumnType("int");

                    b.Property<string>("Sharh")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("image")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Tbl_Derakht_Tajhizat");
                });

            modelBuilder.Entity("pmService.Models.tbl_Catout", b =>
                {
                    b.Property<int>("Code_Catout")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code_Catout"));

                    b.Property<string>("ANE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ANK")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CO")
                        .HasColumnType("int");

                    b.Property<int?>("Code_Parent")
                        .HasColumnType("int");

                    b.Property<string>("GlobalID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Jaryan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name_Catout")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("Noe")
                        .HasColumnType("int");

                    b.Property<string>("Sal_Sakht")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sazande")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("X")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Y")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("hozeh")
                        .HasColumnType("int");

                    b.HasKey("Code_Catout");

                    b.ToTable("tbl_Catout");
                });

            modelBuilder.Entity("pmService.Models.tbl_FFM", b =>
                {
                    b.Property<int>("Code_FFM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code_FFM"));

                    b.Property<string>("ANami_FFM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Bakhsh")
                        .HasColumnType("int");

                    b.Property<string>("BarS_FFM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BarS_Fider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Code_121")
                        .HasColumnType("int");

                    b.Property<string>("Date_FFM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Diagram_FFM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DomadareBa")
                        .HasColumnType("int");

                    b.Property<int?>("DomadareBa2")
                        .HasColumnType("int");

                    b.Property<bool?>("FiderHasas")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Ghati_FFM")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<string>("GlobalID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Havaee_FFM")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<byte?>("KFider_Fider")
                        .HasColumnType("tinyint");

                    b.Property<string>("MAPCODE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MFider_FFM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MetrajDomadareBa1")
                        .HasColumnType("int");

                    b.Property<int?>("MetrajDomadareBa2")
                        .HasColumnType("int");

                    b.Property<byte?>("NFider_FFM")
                        .HasColumnType("tinyint");

                    b.Property<string>("NTef_Fider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NToc_Fider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NTsef_Fider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name_Fider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PFT")
                        .HasColumnType("int");

                    b.Property<string>("SPBar_Fider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Shomareh_Fider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoholateDastresi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TFider_FFM")
                        .HasColumnType("int");

                    b.Property<string>("THef_Fider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("THoc_Fider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("THsef_Fider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TZef_Fider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TZoc_Fider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TZsef_Fider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("X_FFM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Y_FFM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Zamini_FFM")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int?>("hozeh")
                        .HasColumnType("int");

                    b.Property<int?>("noemasraf_ffm")
                        .HasColumnType("int");

                    b.Property<int?>("zamanbandi")
                        .HasColumnType("int");

                    b.HasKey("Code_FFM");

                    b.ToTable("tbl_FFM");
                });

            modelBuilder.Entity("pmService.Models.tbl_Omoor", b =>
                {
                    b.Property<int>("Code_Omoor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code_Omoor"));

                    b.Property<int?>("Daraje_Omoor")
                        .HasColumnType("int");

                    b.Property<string>("GlobalID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Id_Gis")
                        .HasColumnType("int");

                    b.Property<string>("Name_Omoor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Ostan")
                        .HasColumnType("int");

                    b.Property<int?>("Shahr")
                        .HasColumnType("int");

                    b.Property<int?>("code_121")
                        .HasColumnType("int");

                    b.Property<int?>("code_moshtarekin")
                        .HasColumnType("int");

                    b.Property<int?>("id")
                        .HasColumnType("int");

                    b.Property<double?>("lvr")
                        .HasColumnType("float");

                    b.HasKey("Code_Omoor");

                    b.ToTable("tbl_Omoor");
                });

            modelBuilder.Entity("pmService.Models.tbl_PFT", b =>
                {
                    b.Property<int>("Code_PFT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code_PFT"));

                    b.Property<string>("Address_PFT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Date_PFT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ghodrat_PFT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GlobalID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Map_cod_ol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name_PFT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Omoor")
                        .HasColumnType("int");

                    b.Property<string>("Tozihat_PFT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("X_PFT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Y_PFT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Code_PFT");

                    b.ToTable("tbl_PFT");
                });

            modelBuilder.Entity("pmService.Models.tbl_PT", b =>
                {
                    b.Property<int>("Code_PT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code_PT"));

                    b.Property<double?>("Add_Bargiri")
                        .HasColumnType("float");

                    b.Property<string>("Address_PT")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Boof_PT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChaheBarq_PT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChaheNol_PT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Code_Pt_121")
                        .HasColumnType("int");

                    b.Property<long?>("Code_Section_121")
                        .HasColumnType("bigint");

                    b.Property<string>("Code_Section_Gis")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Date_PT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("EmtiazSharayetBargiri")
                        .HasColumnType("float");

                    b.Property<double?>("EmtiazSharayetDoreBazdid")
                        .HasColumnType("float");

                    b.Property<double?>("EmtiazSharayetKhamoshi")
                        .HasColumnType("float");

                    b.Property<double?>("EmtiazSharayetOmomi")
                        .HasColumnType("float");

                    b.Property<string>("Ghodrat_PT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ghodrat_PT2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ghodrat_PT3")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ghodrat_PT4")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("GisObjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("GlobalID")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("GlobalID_1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GlobalID_2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GlobalID_3")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GlobalID_Old")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short?>("Karbari_PT")
                        .HasColumnType("smallint");

                    b.Property<short?>("Karbari_PT_old")
                        .HasColumnType("smallint");

                    b.Property<string>("KhateGarm_PT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MAPCODE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Masir20")
                        .HasColumnType("int");

                    b.Property<string>("Moqavemqt_PT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoshakhaseKelid_PT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name_PT")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("NoeMasraf_PT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("NoeP_PT")
                        .HasColumnType("int");

                    b.Property<string>("NoeSystemZamin_PT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NoeTahviye_PT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Olaviat_Kharabi")
                        .HasColumnType("float");

                    b.Property<string>("Pelak")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Pelak_121_New")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("QFFM")
                        .HasColumnType("int");

                    b.Property<double?>("RCA_Andaze_Ert")
                        .HasColumnType("float");

                    b.Property<double?>("RCA_BarBahrebardari")
                        .HasColumnType("float");

                    b.Property<double?>("RCA_BarPik")
                        .HasColumnType("float");

                    b.Property<bool?>("RCA_Barghgir")
                        .HasColumnType("bit");

                    b.Property<double?>("RCA_JaryanKelid")
                        .HasColumnType("float");

                    b.Property<double?>("RCA_JaryanNami")
                        .HasColumnType("float");

                    b.Property<bool?>("RCA_KablBaghgir")
                        .HasColumnType("bit");

                    b.Property<double?>("RCA_KeshvarSazande")
                        .HasColumnType("float");

                    b.Property<double?>("RCA_TanzimKelid")
                        .HasColumnType("float");

                    b.Property<bool?>("RCA_VaziatSelikajol")
                        .HasColumnType("bit");

                    b.Property<string>("RTU_PT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SakhtemanPost_PT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SalSakht")
                        .HasColumnType("int");

                    b.Property<string>("Shserial_Pt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoholateDastresi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("T_ID_CODE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VaziyatErtebat_PT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("X_PT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Y_PT")
                        .HasColumnType("float");

                    b.Property<int?>("ZamanRaftoBargasht")
                        .HasColumnType("int");

                    b.Property<int?>("ZamanVoghPik")
                        .HasColumnType("int");

                    b.Property<double?>("count_tfz1")
                        .HasColumnType("float");

                    b.Property<double?>("count_tfz2")
                        .HasColumnType("float");

                    b.Property<double?>("emtiaz")
                        .HasColumnType("float");

                    b.Property<int?>("ezafe")
                        .HasColumnType("int");

                    b.Property<int?>("hazf")
                        .HasColumnType("int");

                    b.Property<int?>("hozeh")
                        .HasColumnType("int");

                    b.Property<int?>("zamanbandi")
                        .HasColumnType("int");

                    b.HasKey("Code_PT");

                    b.ToTable("tbl_PT");
                });

            modelBuilder.Entity("pmService.Models.tbl_PayehFFM", b =>
                {
                    b.Property<int>("Code_Payeh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code_Payeh"));

                    b.Property<string>("Address_Payeh")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Code_FFM")
                        .HasColumnType("int");

                    b.Property<int?>("Code_Payeh_121")
                        .HasColumnType("int");

                    b.Property<long?>("Code_Section_121")
                        .HasColumnType("bigint");

                    b.Property<string>("Code_Section_Gis")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double?>("EmtiazSharayetBargiri")
                        .HasColumnType("float");

                    b.Property<double?>("EmtiazSharayetDoreBazdid")
                        .HasColumnType("float");

                    b.Property<double?>("EmtiazSharayetKhamoshi")
                        .HasColumnType("float");

                    b.Property<double?>("EmtiazSharayetOmomi")
                        .HasColumnType("float");

                    b.Property<string>("Ertefa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("GisObjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("GlobalID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GlobalID_1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GlobalID_2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GlobalID_3")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GlobalID_Old")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Keshesh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MAPCODE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NamePayeh")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Noe_Payeh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tozihat_Payeh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("X_Payeh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Y_Payeh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short?>("earth")
                        .HasColumnType("smallint");

                    b.Property<double?>("emtiaz")
                        .HasColumnType("float");

                    b.Property<int?>("hazf")
                        .HasColumnType("int");

                    b.Property<int?>("hozeh")
                        .HasColumnType("int");

                    b.Property<short?>("jelobar")
                        .HasColumnType("smallint");

                    b.Property<int?>("mgh_erth")
                        .HasColumnType("int");

                    b.Property<short?>("noe_arayesh")
                        .HasColumnType("smallint");

                    b.Property<int?>("noe_cheragh")
                        .HasColumnType("int");

                    b.Property<string>("noe_fondasoun")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short?>("noe_kar")
                        .HasColumnType("smallint");

                    b.Property<int?>("num_madar_payeh")
                        .HasColumnType("int");

                    b.Property<int?>("sal_nasb")
                        .HasColumnType("int");

                    b.Property<string>("sal_sakht")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<short?>("sazande")
                        .HasColumnType("smallint");

                    b.Property<int?>("tavan")
                        .HasColumnType("int");

                    b.Property<string>("tedad_mghr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("tole_shabake_dargir")
                        .HasColumnType("float");

                    b.Property<double?>("tole_shabake_moshajjar")
                        .HasColumnType("float");

                    b.Property<short?>("vaz_paye")
                        .HasColumnType("smallint");

                    b.HasKey("Code_Payeh");

                    b.ToTable("tbl_PayehFFM");
                });

            modelBuilder.Entity("pmService.Models.tbl_PayehFFZ", b =>
                {
                    b.Property<int>("Code_Payeh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code_Payeh"));

                    b.Property<string>("Address_Payeh")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("Code_FFZ")
                        .HasColumnType("int");

                    b.Property<short?>("Earth")
                        .HasColumnType("smallint");

                    b.Property<string>("Ertefa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GlobalID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GlobalID_1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GlobalID_2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GlobalID_Old")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short?>("Jelobar")
                        .HasColumnType("smallint");

                    b.Property<string>("Keshesh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MAPCODE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NamePayeh")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Noe_Payeh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sazande")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tozihat_Payeh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("X_Payeh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Y_Payeh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("hazf")
                        .HasColumnType("int");

                    b.Property<int?>("hozeh")
                        .HasColumnType("int");

                    b.Property<int?>("mgh_erth")
                        .HasColumnType("int");

                    b.Property<short?>("noe_arayesh_paye")
                        .HasColumnType("smallint");

                    b.Property<int?>("noe_cheragh")
                        .HasColumnType("int");

                    b.Property<string>("noe_fondasoun")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short?>("noe_kar")
                        .HasColumnType("smallint");

                    b.Property<string>("sal_nasb")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("sal_sakht")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("tavan")
                        .HasColumnType("int");

                    b.Property<double?>("tole_shabake_moshajjar")
                        .HasColumnType("float");

                    b.Property<short?>("vaz_paye")
                        .HasColumnType("smallint");

                    b.HasKey("Code_Payeh");

                    b.ToTable("tbl_PayehFFZ");
                });

            modelBuilder.Entity("pmService.Models.tbl_QFFM", b =>
                {
                    b.Property<int>("Code_QFFM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code_QFFM"));

                    b.Property<string>("AddressM_QFFM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Bakhsh")
                        .HasColumnType("int");

                    b.Property<string>("EbMasir_QFFM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("EmtiazSharayetBargiri")
                        .HasColumnType("float");

                    b.Property<double?>("EmtiazSharayetDoreBazdid")
                        .HasColumnType("float");

                    b.Property<double?>("EmtiazSharayetKhamoshi")
                        .HasColumnType("float");

                    b.Property<double?>("EmtiazSharayetOmomi")
                        .HasColumnType("float");

                    b.Property<string>("EnMasir_QFFM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Fider")
                        .HasColumnType("int");

                    b.Property<string>("GlobalID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Havaee_QFFM")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("JMasir_QFFM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Maqta")
                        .HasColumnType("int");

                    b.Property<int?>("Moshajjar_QFFM")
                        .HasColumnType("int");

                    b.Property<string>("NMasir_QFFM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte?>("NShabakeh_QFFM")
                        .HasColumnType("tinyint");

                    b.Property<int?>("NoeHadi")
                        .HasColumnType("int");

                    b.Property<int?>("TKMasir_QFFM")
                        .HasColumnType("int");

                    b.Property<string>("Xp_QFFM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Xsh_QFFM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Yp_QFFM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ysh_QFFM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ZamanRaftoBargasht")
                        .HasColumnType("int");

                    b.Property<decimal?>("Zamini_QFFM")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<double?>("emtiaz")
                        .HasColumnType("float");

                    b.Property<int?>("hozeh")
                        .HasColumnType("int");

                    b.HasKey("Code_QFFM");

                    b.ToTable("tbl_QFFM");
                });

            modelBuilder.Entity("pmService.Models.tbl_Secsuner", b =>
                {
                    b.Property<int>("Code_Secsuner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code_Secsuner"));

                    b.Property<int?>("CO")
                        .HasColumnType("int");

                    b.Property<int?>("Code_Parent")
                        .HasColumnType("int");

                    b.Property<string>("GlobalID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name_Secsuner")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("NoeSecsuner")
                        .HasColumnType("int");

                    b.Property<int?>("PT")
                        .HasColumnType("int");

                    b.Property<string>("Sal_Sakht")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sazande")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("hozeh")
                        .HasColumnType("int");

                    b.HasKey("Code_Secsuner");

                    b.ToTable("tbl_Secsuner");
                });

            modelBuilder.Entity("pmService.Models.tbl_Tablo", b =>
                {
                    b.Property<int>("Code_Tablo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code_Tablo"));

                    b.Property<int?>("CO")
                        .HasColumnType("int");

                    b.Property<string>("CT_Tablo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Code_Parent")
                        .HasColumnType("int");

                    b.Property<byte?>("Connect_Tablo")
                        .HasColumnType("tinyint");

                    b.Property<string>("Date_Tablo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ertelektriki")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Erthefazati")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GKelid_Tablo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Maqta_Tablo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name_Tablo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PT")
                        .HasColumnType("int");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TedadCell_Tablo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TedadTablo_Tablo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("globalid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("hozeh")
                        .HasColumnType("int");

                    b.Property<string>("sale_nasb")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("sale_sakht")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("sazande")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Code_Tablo");

                    b.ToTable("tbl_Tablo");
                });

            modelBuilder.Entity("pmService.Models.tbl_Trance", b =>
                {
                    b.Property<int>("Code_Trance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code_Trance"));

                    b.Property<int?>("Code_Parent")
                        .HasColumnType("int");

                    b.Property<string>("Name_Trance")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("globalid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("hozeh")
                        .HasColumnType("int");

                    b.Property<string>("sale_nasb")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("sale_sakht")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("sazande")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("zarfiat")
                        .HasColumnType("int");

                    b.HasKey("Code_Trance");

                    b.ToTable("tbl_Trance");
                });

            modelBuilder.Entity("PmServiceNetCode.Models.EndpointPermission", b =>
                {
                    b.HasOne("PmServiceNetCode.Models.Endpoint", "Endpoint")
                        .WithMany("EndpointPermissions")
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PmServiceNetCode.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endpoint");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("PmServiceNetCode.Models.RolePermission", b =>
                {
                    b.HasOne("PmServiceNetCode.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PmServiceNetCode.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PmServiceNetCode.Models.UserRole", b =>
                {
                    b.HasOne("PmServiceNetCode.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PmServiceNetCode.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PmServiceNetCode.Models.Endpoint", b =>
                {
                    b.Navigation("EndpointPermissions");
                });

            modelBuilder.Entity("PmServiceNetCode.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("PmServiceNetCode.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("PmServiceNetCode.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
